SC_LINKS = ["all-music", "indie", "electronic", "rbsoul", "classical", "pop", "folksingersongwriter", "hiphoprap"]

SOUNDCLOUD_CHART_HEADERS = [
  "CHART POS",
  "ARTIST",
  "TRACK",
  "FACEBOOK LIKES",
  "SPOTIFY POPULARITY",
  "LABEL INFO FROM FB",
  "GENERAL MANAGER INFO FROM FB",
  "PROFILE NAME FROM FB",
  "ARTIST WEBSITE LINKS",
  "SPOTIFY ARTIST LINK",
  "GENRE FROM FB",
  "SOUNDCLOUD LIKES COUNT",
  "SOUNDCLOUD PLAYBACK COUNT",
  "SOUNDCLOUD CHART SOURCE",
  "TIME OF SONG DATA SCRAPING"
]

SPOTIFY_PLAYLIST_HEADERS = [
  "SONG POS",
  "ARTIST",
  "TRACK",
  "FACEBOOK LIKES",
  "SPOTIFY POPULARITY",
  "LABEL INFO FROM FB",
  "GENERAL MANAGER INFO FROM FB",
  "PROFILE NAME FROM FB",
  "ARTIST WEBSITE LINKS",
  "SPOTIFY ARTIST LINK",
  "GENRE FROM FB",
  "TRACK TEMPO",
  "TRACK DANCIBILITY SCORE",
  "TRACK INSTRUMENTALNESS SCORE",
  "TRACK POSITIVENESS SCORE",
  "SPOTIFY PLAYLIST SOURCE",
  "TIME OF SONG DATA SCRAPING"
]